#!/bin/sh

for duck in *.duck; do
    page=$(echo $duck | sed -e 's/\.duck$/.page/')
    if [ ! -f "$page" ]; then
        echo $duck;
    else
        python3 ../ducktype/__init__.py $duck | cmp - $page || echo $duck
    fi
done
